name: Latest Blog Posts

on:
  schedule:
    # Runs automatically every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

jobs:
  update-readme-with-blog:
    name: Update README with RSS feeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@mrphatom"
          max_post_count: 5
